version: "3.8"

services:
  postgres:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=user_service_db_docker
      - POSTGRES_USER=my_name_docker
      - POSTGRES_PASSWORD=my_password_docker
    ports:
      - "5432:5432"
  redis:
    image: redis:8.2
    ports:
      - "6379:6379"