spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db_docker
    username: my_name_docker
    password: my_password_docker
  data:
    redis:
      host: localhost
      port: 6379