spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db_local
    username: my_name_local
    password: my_password_local
  data:
    redis:
      host: localhost
      port: 6379