name: CI pipeline

on:
  push:
    branches: ["CIPipeline"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Permission to execute grablew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --no-daemon