name: CI pipeline

on:
  push:
    branches: ["CIPipeline"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Permission to execute gradlew
        run: chmod +x "User Service/gradlew"

      - name: Build
        run: "./User Service/gradlew build --no-daemon"
